=begin
#Brightcove Analytics API Reference

#Reference for the Brightcove Analytics API, used to retrieve analytics data for your accounts. To test API requests, you can use our <a href=\"/getting-started/concepts-testing-tools-brightcove-apis.html\" target=\"_blank\">API Testing Tools</a>.  For additional in-depth guides to features of the API, see the **[general documentation](/analytics/index.html)**.   **Base URL**: https://analytics.api.brightcove.com

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class Where
    ACCOUNT = "account".freeze
    CITY = "city".freeze
    COUNTRY = "country".freeze
    REGION = "region".freeze
    DATE = "date".freeze
    DATE_TIME = "date-time".freeze
    DEVICE_OS = "device_os".freeze
    DEVICE_TYPE = "device_type".freeze
    PLAYER = "player".freeze
    REFERRER_DOMAIN = "referrer_domain".freeze
    DESTINATION_DOMAIN = "destination_domain".freeze
    SEARCH_TERMS = "search_terms".freeze
    SOCIAL_PLATFORM = "social_platform".freeze
    SOURCE_TYPE = "source_type".freeze
    VIDEO = "video".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Where.constants.select { |c| Where::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Where" if constantValues.empty?
      value
    end
  end
end
