=begin
#Brightcove Analytics API Reference

#Reference for the Brightcove Analytics API, used to retrieve analytics data for your accounts. To test API requests, you can use our <a href=\"/getting-started/concepts-testing-tools-brightcove-apis.html\" target=\"_blank\">API Testing Tools</a>.  For additional in-depth guides to features of the API, see the **[general documentation](/analytics/index.html)**.   **Base URL**: https://analytics.api.brightcove.com

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::EngagementReportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EngagementReportApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::EngagementReportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EngagementReportApi' do
    it 'should create an instance of EngagementReportApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::EngagementReportApi)
    end
  end

  # unit tests for get_account_engagement
  # Get Account Engagement
  # Get a summary report of engagement for the account. Note:  Engagement reports are only available for periods within the past 32 days. Requests outside that range will return an error The only parameters supported for Engagement reports are from and to Engagement reports are available for single accounts only - reports on multiple accounts will not work
  # @param account_id a Video Cloud account ID
  # @param content_type Content-Type: application/json
  # @param authorization Authorization: Bearer access_token (see Getting Access Tokens)
  # @param accept_encoding Accept-Encoding: gzip (optional)
  # @param [Hash] opts the optional parameters
  # @return [Timeline]
  describe 'get_account_engagement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_player_engagement
  # Get Player Engagement
  # Get a summary report of engagement for a player. Note:  Engagement reports are only available for periods within the past 32 days. Requests outside that range will return an error The only parameters supported for Engagement reports are from and to Engagement reports are available for single accounts only - reports on multiple accounts will not work
  # @param account_id a Video Cloud account ID
  # @param content_type Content-Type: application/json
  # @param authorization Authorization: Bearer access_token (see Getting Access Tokens)
  # @param accept_encoding Accept-Encoding: gzip (optional)
  # @param player_id a Video Cloud player ID
  # @param [Hash] opts the optional parameters
  # @return [Timeline]
  describe 'get_player_engagement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_video_engagement
  # Get Video Engagement
  # Get a summary report of engagement for a video. Note:  Engagement reports are only available for periods within the past 32 days. Requests outside that range will return an error The only parameters supported for Engagement reports are from and to Engagement reports are available for single accounts only - reports on multiple accounts will not work
  # @param account_id a Video Cloud account ID
  # @param content_type Content-Type: application/json
  # @param authorization Authorization: Bearer access_token (see Getting Access Tokens)
  # @param accept_encoding Accept-Encoding: gzip (optional)
  # @param video_id a Video Cloud video ID
  # @param [Hash] opts the optional parameters
  # @return [GetVideoEngagementResponse]
  describe 'get_video_engagement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
