=begin
#Brightcove Analytics API Reference

#Reference for the Brightcove Analytics API, used to retrieve analytics data for your accounts. To test API requests, you can use our <a href=\"/getting-started/concepts-testing-tools-brightcove-apis.html\" target=\"_blank\">API Testing Tools</a>.  For additional in-depth guides to features of the API, see the **[general documentation](/analytics/index.html)**.   **Base URL**: https://analytics.api.brightcove.com

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LiveAnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LiveAnalyticsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LiveAnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LiveAnalyticsApi' do
    it 'should create an instance of LiveAnalyticsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LiveAnalyticsApi)
    end
  end

  # unit tests for get_live_events
  # Get Live Analytics event
  # Provides a summary of analytics data collected for a live stream.
  # @param content_type Content-Type: application/json
  # @param authorization Authorization: Bearer access_token (see Getting Access Tokens)
  # @param accept_encoding Accept-Encoding: gzip (optional)
  # @param account_id a Video Cloud account ID
  # @param dimensions_for_live_analytics One or more dimensions to report on for Live Analytics requests Dimensions:   - video   - video, country   - video, device_type
  # @param metrics Data metrics to return for live analytics requests:    - &#x60;video_impression&#x60; - the number of video impressions   - &#x60;video_view&#x60; - the number of video views   - &#x60;video_seconds_viewed&#x60; - seconds of video viewed   - &#x60;alive_ss_ad_start&#x60; - SSAI ad starts   - &#x60;fingerprint_count&#x60; - \&quot;fingerprint\&quot; (user) count   - &#x60;ccu&#x60; - concurrent viewers
  # @param filters_for_live_analytics One or more filters to limit responses for Live Analytics requests Available filters:   - video   - country   - device_type
  # @param [Hash] opts the optional parameters
  # @return [GetEventsResponse]
  describe 'get_live_events test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_live_time_series
  # Get Live Analytics time-series
  # A time-series is defined as a an list of timestamp-value pairs representing samples of a variable (metric). The time-series API intends to allow the user to return a time-series for the set of metrics requested in the query.
  # @param content_type Content-Type: application/json
  # @param authorization Authorization: Bearer access_token (see Getting Access Tokens)
  # @param accept_encoding Accept-Encoding: gzip (optional)
  # @param account_id a Video Cloud account ID
  # @param dimensions_for_live_analytics One or more dimensions to report on for Live Analytics requests Dimensions:   - video   - video, country   - video, device_type
  # @param metrics Data metrics to return for live analytics requests:    - &#x60;video_impression&#x60; - the number of video impressions   - &#x60;video_view&#x60; - the number of video views   - &#x60;video_seconds_viewed&#x60; - seconds of video viewed   - &#x60;alive_ss_ad_start&#x60; - SSAI ad starts   - &#x60;fingerprint_count&#x60; - \&quot;fingerprint\&quot; (user) count   - &#x60;ccu&#x60; - concurrent viewers
  # @param where one or more &#39;dimension&#x3D;&#x3D;value&#39; pairs to filter the results; for live, the only available filters are &#x60;country&#x60;, &#x60;device-type&#x60;, and &#x60;video&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :bucket_limit &#39;Max number of points to be returned for a time-series&#39;
  # @option opts [String] :bucket_duration &#39;Intervals duration in the form of an integer plus &#x60;m&#x60; (minutes), &#x60;h&#x60; (hours), or &#x60;d&#x60; (days)&#39;
  # @option opts [OneOfstringinteger] :from &#39;Start time for the period covered by the report — epoch time in milliseconds (&#x60;1535654206775&#x60;) or a date in the format &#x60;yyyy-mm-dd&#x60; (such as &#x60;2013-09-26&#x60;)&#39;
  # @option opts [OneOfstringinteger] :to End time for the period covered by the report — &#x60;now&#x60; or epoch time in milliseconds (&#x60;1535654206775&#x60;) or a date in the format &#x60;yyyy-mm-dd&#x60; (such as &#x60;2013-09-26&#x60;)
  # @return [GetTimeSeriesResponse]
  describe 'get_live_time_series test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
